import { ReactNode } from 'react';

import type { Metadata } from 'next';

import '@/assets/globals.css';

import { ClerkProvider } from '@clerk/nextjs';

import { ThemeProvider } from '@/components/theme/theme-provider';
import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';

import { cn } from '@/lib/utils';

import { geistMono, geistSans } from '@/assets/fonts';

import { QueryProvider } from '@/providers/query-provider';
import { SheetProvider } from '@/providers/sheet-provider';

export const metadata: Metadata = {
  title: {
    default: 'Cash In Hand',
    template: '%s | Cash In Hand',
  },
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            'w-full min-h-screen font-sans antialiased',
            geistMono.variable,
            geistSans.variable,
          )}
        >
          <ThemeProvider attribute="class" defaultTheme="dark">
            <TooltipProvider>
              <QueryProvider>
                <SheetProvider />
                <Toaster />
                {children}
              </QueryProvider>
            </TooltipProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
